// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VentasBackend.Infrastructure.Data;

#nullable disable

namespace VentasBackend.Migrations
{
    [DbContext(typeof(VentasDbContext))]
    partial class VentasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ventas")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VentasBackend.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdEmpresa", "Telefono");

                    b.ToTable("clientes", "ventas");
                });

            modelBuilder.Entity("VentasBackend.Domain.Entities.ConfiguracionVentas", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_configuracion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConfiguracion"));

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<string>("NombreImpuesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_impuesto");

                    b.Property<decimal>("PorcentajeImpuesto")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_impuesto");

                    b.HasKey("IdConfiguracion");

                    b.HasIndex("IdEmpresa")
                        .IsUnique();

                    b.ToTable("ConfiguracionVentas", "ventas");
                });

            modelBuilder.Entity("VentasBackend.Domain.Entities.CuentaTicket", b =>
                {
                    b.Property<int>("IdCuentaTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cuenta_ticket");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCuentaTicket"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<int>("IdAlmacen")
                        .HasColumnType("integer")
                        .HasColumnName("id_almacen");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("impuesto");

                    b.Property<string>("Mesero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mesero");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.HasKey("IdCuentaTicket");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpresa", "Estado");

                    b.HasIndex("IdEmpresa", "Numero")
                        .IsUnique();

                    b.ToTable("cuentas_tickets", "ventas");
                });

            modelBuilder.Entity("VentasBackend.Domain.Entities.CuentaTicketItem", b =>
                {
                    b.Property<int>("IdCuentaTicketItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cuenta_ticket_item");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCuentaTicketItem"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("EstadoComanda")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_comanda");

                    b.Property<int>("IdCuentaTicket")
                        .HasColumnType("integer")
                        .HasColumnName("id_cuenta_ticket");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<string>("Nota")
                        .HasColumnType("text")
                        .HasColumnName("nota");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("IdCuentaTicketItem");

                    b.HasIndex("EstadoComanda");

                    b.HasIndex("IdCuentaTicket");

                    b.HasIndex("IdProducto");

                    b.ToTable("cuentas_ticket_items", "ventas");
                });

            modelBuilder.Entity("VentasBackend.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpresa"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("Nombre");

                    b.ToTable("Empresas", "shared", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("VentasBackend.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdCuentaTicket")
                        .HasColumnType("integer")
                        .HasColumnName("id_cuenta_ticket");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.HasKey("IdPago");

                    b.HasIndex("FechaPago");

                    b.HasIndex("IdCuentaTicket");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("pagos", "ventas");
                });

            modelBuilder.Entity("VentasBackend.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("VentasBackend.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VentasBackend.Domain.Entities.CuentaTicket", b =>
                {
                    b.HasOne("VentasBackend.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VentasBackend.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VentasBackend.Domain.Entities.CuentaTicketItem", b =>
                {
                    b.HasOne("VentasBackend.Domain.Entities.CuentaTicket", null)
                        .WithMany()
                        .HasForeignKey("IdCuentaTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VentasBackend.Domain.Entities.Pago", b =>
                {
                    b.HasOne("VentasBackend.Domain.Entities.CuentaTicket", null)
                        .WithMany()
                        .HasForeignKey("IdCuentaTicket")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VentasBackend.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
